Deviseでユーザー認証機能追加
kasai441/fjord-books_app pull request #3
Opened 2021-02-22 08:12 UTC by kasai441

2021-03-01 03:28 UTC, komagata requested changes

2021-03-01 03:28 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(10)
`10`がマジックナンバーになっているのでkaminariの機能か定数などにしたいですね。

2021-03-01 03:28 UTC, komagata commented on app/views/books/_form.html.erb
> +</div>
最終行に改行がないようです。大抵のエディターで自動的に入るように設定できるので試してみてください〜

2021-03-01 03:28 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
[よくあるミス](https://bootcamp.fjord.jp/practices/40#honest-mistake)にあるようにdevise-i18nを使っている場合はgemの中にこのファイルがあるので自分のリポジトリの方には含めなくて大丈夫です〜

2021-03-01 03:28 UTC, komagata commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
これらの使ってないファイルは不要なので削除しちゃってください〜

2021-03-01 03:28 UTC, komagata commented on test/models/user_test.rb
> +# frozen_string_literal: true
これらの使ってないファイルは不要なので削除しちゃってください〜

2021-03-01 08:18 UTC, kasai441 commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(10)
コンフィグファイルに数値を設定するようにしました
https://github.com/kasai441/fjord-books_app/pull/3/commits/3adcc77a3d416c9ff144c2575f34125a0d93bd65

2021-03-01 08:21 UTC, kasai441 commented
@komagata 
修正しましたー！
注意事項に書いてあるミスを連発しておりました、チェックが甘かったと反省しています...

2021-03-01 13:49 UTC, komagata requested changes

2021-03-01 13:49 UTC, komagata commented on app/assets/stylesheets/scaffolds.scss
> +/*
gitでバージョン管理しているのでコードをコメントにして残しておく必要はありません。（簡単に昔の状態に戻せるからです）

なのでコメントアウトするのであれば削除しちゃってください〜

2021-03-02 01:09 UTC, kasai441 commented
@komagata 
不要ファイル削除しました！

2021-03-02 05:39 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-02 05:39 UTC, komagata commented on config/initializers/kaminari_config.rb
> +  config.default_per_page = 10
👍

2021-03-02 05:39 UTC, komagata commented on db/seeds.rb
> +User.create!(
seedで初期データを入れるのはとってもいい習慣ですね！

2021-03-02 08:36 UTC, merged